sudo: required
language: generic
service:
  - docker

before_install:
  - docker build -t lakegel09/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lakegel09/docker-react npm run test